name: CI/CD Next.js

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape de débogage pour afficher la structure des fichiers
      - name: Debug - List files and structure
        run: |
          pwd
          echo "--- Directory structure ---"
          find . -type d
          echo "--- All files ---"
          find . -type f
          echo "--- Searching for specific files ---"
          find . -name "mouse-move-effect.tsx"
          find . -name "tsconfig.json"
          

      # Afficher le contenu de tsconfig.json
      - name: Show tsconfig.json content
        run: cat tsconfig.json

      # Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # Vérification du code avec ESLint
      - name: Lint code
        run: npm run lint || echo "Linting failed"

      # Construire le projet avec des logs détaillés
      - name: Build project
        run: |
          npm run build --verbose
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      # Exécuter les tests (si configurés)
      - name: Run tests
        run: npm test || echo "No tests configured"

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-nextjs:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-nextjs:${{ github.sha }}